// prisma/seed/modules.ts
// Using string types instead of enums for SQLite compatibility

export const MODULES: Array<{
  id: string; name: string; domain: string; defaultVirtue: string;
  description?: string; philosophy?: string; scienceNotes?: string;
  contraindications?: string; commonMistakes?: string; coachingPrompts?: string; measurement?: string;
}> = [
  // Mind & Mental Mastery
  { id:"breathwork", name:"Breathwork", domain:"Mind", defaultVirtue:"Temperance",
    description:"Train breath to modulate state (calm, focus, energy).",
    scienceNotes:"Paced nasal breathing supports vagal tone; CO2 tolerance matters.",
    contraindications:"Stop if dizzy; avoid extreme breath holds with cardiac risk or pregnancy.",
    measurement:"minutes, protocol, mood delta (1–5)" },
  { id:"meditation", name:"Meditation & Stillness", domain:"Mind", defaultVirtue:"Wisdom",
    description:"Attention training and friendly awareness.",
    contraindications:"Shorten/eyes-open if anxious; trauma-sensitive pacing.",
    measurement:"minutes, style, mood delta, notes" },
  { id:"visualization", name:"Visualization & Mental Rehearsal", domain:"Mind", defaultVirtue:"Courage",
    description:"Rehearse identity-aligned actions vividly.",
    contraindications:"Avoid catastrophizing imagery.",
    measurement:"minutes, vividness (1–5), next action" },
  { id:"memory_training", name:"Memory & Brain Training", domain:"Mind", defaultVirtue:"Wisdom",
    description:"Practical memory systems: loci, hooks, spaced repetition.",
    measurement:"items recalled, accuracy %, review cadence" },
  { id:"focus_deepwork", name:"Focus & Deep Work", domain:"Mind", defaultVirtue:"Temperance",
    description:"Protected blocks for hard, meaningful work.",
    measurement:"blocks completed, interruptions, depth (1–5)" },
  { id:"mood_regulation", name:"Mood & Emotional Regulation", domain:"Mind", defaultVirtue:"Temperance",
    description:"Name, normalize, navigate emotions skillfully.",
    measurement:"mood trend, triggers, reappraisal notes" },

  // Body & Vitality
  { id:"fasting", name:"Fasting & Nutrition Timing", domain:"Body", defaultVirtue:"Temperance",
    description:"Gentle time-restricted eating for clarity & discipline.",
    contraindications:"Not for ED hx; medical conditions need clinician guidance.",
    measurement:"window start/stop, hours, clarity score" },
  { id:"hydration", name:"Hydration & Mineral Balance", domain:"Body", defaultVirtue:"Temperance",
    description:"Meet fluid + electrolyte needs for cognition & energy.",
    contraindications:"Hyponatremia risk if overconsuming plain water.",
    measurement:"mL/day, mineral adds, timing" },
  { id:"cold_heat", name:"Cold & Heat Exposure", domain:"Body", defaultVirtue:"Courage",
    description:"Hormetic stress (cold/heat) applied safely.",
    contraindications:"Cardiac issues/pregnancy require clearance. Never breath-hold in water.",
    measurement:"temp (approx), duration, RPE, mood delta" },
  { id:"movement_posture", name:"Movement & Posture", domain:"Body", defaultVirtue:"Justice",
    description:"Mobility, gait, posture as confidence & function.",
    measurement:"steps, mobility minutes, posture checks" },
  { id:"strength", name:"Strength & Functional Training", domain:"Body", defaultVirtue:"Courage",
    description:"Push, pull, squat, hinge, carry for real-world capability.",
    measurement:"sets, reps, RPE, pattern focus" },
  { id:"flexibility", name:"Flexibility & Longevity Flow", domain:"Body", defaultVirtue:"Temperance",
    description:"Gentle stretches/flows to sustain range & ease.",
    measurement:"minutes, regions, ease score" },
  { id:"sleep_circadian", name:"Sleep & Circadian Rhythm", domain:"Body", defaultVirtue:"Wisdom",
    description:"Light, temperature, timing to restore.",
    measurement:"bed/wake, AM light minutes, sleep quality (1–5)" },
  { id:"skin_care", name:"Skin, Hair & Physical Care", domain:"Body", defaultVirtue:"Temperance",
    description:"Barrier basics: cleanse, protect, nourish, recover.",
    measurement:"routine adherence, irritation flags, sun timing" },
  { id:"longevity", name:"Longevity Protocols", domain:"Body", defaultVirtue:"Wisdom",
    description:"Zone-2, resistance, sleep, protein, connection.",
    measurement:"weekly zone-2, strength sessions, sleep score, social touches" },

  // Spirit & Awareness
  { id:"virtue_cultivation", name:"Virtue Cultivation", domain:"Spirit", defaultVirtue:"All",
    description:"Small daily acts of Wisdom, Courage, Justice, Temperance.",
    measurement:"virtue acts logged; reflection" },
  { id:"philosophy_capsules", name:"Philosophy Capsules", domain:"Spirit", defaultVirtue:"Wisdom",
    description:"Actionable micro-lessons from classic works.",
    measurement:"capsules completed; practice linked; reflection" },
  { id:"gratitude_awe", name:"Gratitude & Awe", domain:"Spirit", defaultVirtue:"Justice",
    description:"Train appreciation and wonder; expand capacity.",
    measurement:"gratitudes/day; awe moments/week" },
  { id:"service_contribution", name:"Service & Contribution", domain:"Spirit", defaultVirtue:"Justice",
    description:"Turn capacity outward with small, consistent help.",
    measurement:"acts/week; hours volunteered; impact notes" },
  { id:"memento_mori", name:"Death Awareness (Memento Mori)", domain:"Spirit", defaultVirtue:"Wisdom",
    description:"Remember finitude to clarify priorities & love.",
    measurement:"frequency; value-aligned actions; relationship touches" },

  // Community & Social
  { id:"etiquette_presence", name:"Etiquette & Presence", domain:"Community", defaultVirtue:"Justice",
    description:"Warmth + clarity via greeting, posture, voice.",
    measurement:"greetings/day; thank-yous; listening ratio" },
  { id:"active_listening", name:"Active Listening & Empathy", domain:"Community", defaultVirtue:"Justice",
    description:"Reflect, clarify, honor silence.",
    measurement:"reflections/day; corrections; tension drop" },
  { id:"conflict_debate", name:"Conflict & Debate Training", domain:"Community", defaultVirtue:"Courage",
    description:"Steelman, nonviolent messages, third-way options.",
    measurement:"conflicts cooled; agreements reached" },
  { id:"mentorship_teaching", name:"Mentorship & Teaching", domain:"Community", defaultVirtue:"Wisdom",
    description:"Teach to learn; lift as you climb.",
    measurement:"mentee touches; lessons; feedback" },
  { id:"tribal_challenges", name:"Tribal Challenges", domain:"Community", defaultVirtue:"Justice",
    description:"Group streaks & shared rituals for identity.",
    measurement:"group streak days; invites; participants" },

  // Knowledge & Learning
  { id:"resource_library", name:"Resource Library", domain:"Knowledge", defaultVirtue:"Wisdom",
    description:"Living library—distilled classics into action.",
    measurement:"capsules completed; notes; teaching" },
  { id:"hidden_wisdom", name:"Daily Hidden Wisdom Unlocks", domain:"Knowledge", defaultVirtue:"Wisdom",
    description:"1 surprise insight/day with micro-experiment.",
    measurement:"insight opened; experiment done; reflection" },
  { id:"skill_builder", name:"Skill Builder Modules", domain:"Knowledge", defaultVirtue:"Wisdom",
    description:"Finance, logic, rhetoric, speed reading basics.",
    measurement:"skill reps; quiz accuracy; project milestone" },
  { id:"language_memory", name:"Language & Memory Expansion", domain:"Knowledge", defaultVirtue:"Wisdom",
    description:"Daily word + palace hook + usage.",
    measurement:"words learned; recall; usage" },
  { id:"creative_spark", name:"Creative Spark", domain:"Knowledge", defaultVirtue:"Courage",
    description:"3–5 min play: draw, write, sing, move.",
    measurement:"outputs/week; joy rating; shares" },
]; 