// prisma/seed/resources-data.ts
export const RESOURCES = [
  // Stoic Resources
  { id:"meditations_capsule_intro", title:"Meditations — What is in my control?",
    thinker:"Marcus Aurelius", era:"Classical", type:"capsule", estMinutes:3, level:"Beginner",
    keyIdeas:["Control vs not control","Inner citadel","Present duty"],
    microPractices:["List 3 controllables today","Release 1 uncontrollable"], 
    reflections:["What duty lies nearest?"], audioUrl:null },
  { id:"nicomachean_ethics_capsule_mean", title:"Nicomachean Ethics — Virtue as the Mean",
    thinker:"Aristotle", era:"Classical", type:"capsule", estMinutes:3, level:"Beginner",
    keyIdeas:["Habit builds character","Mean between extremes"],
    microPractices:["Choose one temperance act today"], 
    reflections:["Where did I choose the mean today?"], audioUrl:null },
  { id:"epictetus_handbook", title:"Enchiridion — The Art of Living",
    thinker:"Epictetus", era:"Classical", type:"capsule", estMinutes:5, level:"Beginner",
    keyIdeas:["Accept what happens","Focus on your choices","Practice daily"],
    microPractices:["Accept one difficulty today","Choose your response"], 
    reflections:["What can I control in this moment?"], audioUrl:null },

  // Spartan Resources
  { id:"plutarch_lycurgus", title:"Life of Lycurgus — Spartan Discipline",
    thinker:"Plutarch", era:"Classical", type:"capsule", estMinutes:4, level:"Intermediate",
    keyIdeas:["Embrace hardship","Discipline for freedom","Service to community"],
    microPractices:["Cold shower challenge","Complete one hard task"], 
    reflections:["What discomfort did I embrace today?"], audioUrl:null },
  { id:"xenophon_education", title:"Education of Cyrus — Leadership Through Example",
    thinker:"Xenophon", era:"Classical", type:"capsule", estMinutes:4, level:"Intermediate",
    keyIdeas:["Lead by example","Endurance builds character","Simplicity in leadership"],
    microPractices:["Model one virtue today","Simplify one decision"], 
    reflections:["How did I lead through action today?"], audioUrl:null },

  // Bushido Resources
  { id:"hagakure_way", title:"Hagakure — The Way of the Samurai",
    thinker:"Yamamoto Tsunetomo", era:"Edo Period", type:"capsule", estMinutes:4, level:"Intermediate",
    keyIdeas:["Death awareness","Loyalty and honor","Every moment matters"],
    microPractices:["Live as if today is your last","Honor one commitment"], 
    reflections:["How did I honor my word today?"], audioUrl:null },
  { id:"bushido_spirit", title:"Bushido: The Soul of Japan",
    thinker:"Inazo Nitobe", era:"Meiji Period", type:"capsule", estMinutes:5, level:"Beginner",
    keyIdeas:["Rectitude and justice","Courage and benevolence","Polite courtesy"],
    microPractices:["Practice one act of courtesy","Show courage in small ways"], 
    reflections:["How did I demonstrate honor today?"], audioUrl:null },

  // Monastic Resources
  { id:"rule_benedict", title:"Rule of St. Benedict — Order and Stability",
    thinker:"St. Benedict", era:"Medieval", type:"capsule", estMinutes:4, level:"Beginner",
    keyIdeas:["Ora et labora","Stability and community","Humility in all things"],
    microPractices:["Create one moment of silence","Serve someone today"], 
    reflections:["How did I practice humility today?"], audioUrl:null },
  { id:"desert_fathers", title:"Sayings of the Desert Fathers — Simplicity",
    thinker:"Various", era:"Early Christian", type:"capsule", estMinutes:3, level:"Beginner",
    keyIdeas:["Simplicity of heart","Watchfulness","Gentle discipline"],
    microPractices:["Simplify one choice today","Practice watchfulness"], 
    reflections:["What did I learn from simplicity today?"], audioUrl:null },

  // Yogic Resources
  { id:"yoga_sutras", title:"Yoga Sutras — The Eightfold Path",
    thinker:"Patanjali", era:"Classical India", type:"capsule", estMinutes:5, level:"Intermediate",
    keyIdeas:["Yama and niyama","Asana and pranayama","Meditation and samadhi"],
    microPractices:["Practice one yama today","Simple asana sequence"], 
    reflections:["How did I practice non-harm today?"], audioUrl:null },
  { id:"bhagavad_gita", title:"Bhagavad Gita — Duty and Devotion",
    thinker:"Krishna", era:"Classical India", type:"capsule", estMinutes:6, level:"Intermediate",
    keyIdeas:["Dharma and duty","Detached action","Devotion to higher purpose"],
    microPractices:["Do your duty without attachment","Practice devotion"], 
    reflections:["What is my dharma in this moment?"], audioUrl:null },

  // Indigenous Resources
  { id:"seven_grandfathers", title:"Seven Grandfather Teachings — Wisdom of the Anishinaabe",
    thinker:"Anishinaabe Elders", era:"Timeless", type:"capsule", estMinutes:4, level:"Beginner",
    keyIdeas:["Love, respect, courage","Honesty, wisdom, humility","Truth"],
    microPractices:["Practice one grandfather teaching","Connect with nature"], 
    reflections:["How did I honor the earth today?"], audioUrl:null },
  { id:"indigenous_stewardship", title:"Indigenous Stewardship — Caring for Creation",
    thinker:"Various Indigenous Peoples", era:"Timeless", type:"capsule", estMinutes:4, level:"Beginner",
    keyIdeas:["Interconnectedness","Gratitude for gifts","Responsibility to future"],
    microPractices:["Express gratitude for nature","Care for one living thing"], 
    reflections:["How did I steward creation today?"], audioUrl:null },

  // Martial Arts Resources
  { id:"art_war", title:"Art of War — Strategy and Discipline",
    thinker:"Sun Tzu", era:"Ancient China", type:"capsule", estMinutes:5, level:"Intermediate",
    keyIdeas:["Know yourself and enemy","Adapt to circumstances","Discipline wins"],
    microPractices:["Assess your strengths today","Adapt to one challenge"], 
    reflections:["How did I apply strategy today?"], audioUrl:null },
  { id:"zen_mind", title:"Zen Mind, Beginner's Mind — Martial Spirit",
    thinker:"Shunryu Suzuki", era:"Modern", type:"capsule", estMinutes:4, level:"Beginner",
    keyIdeas:["Beginner's mind","Present moment awareness","Natural discipline"],
    microPractices:["Approach one task with beginner's mind","Practice presence"], 
    reflections:["How did I maintain beginner's mind today?"], audioUrl:null },

  // Sufi Resources
  { id:"rumi_poetry", title:"Rumi — Love and Remembrance",
    thinker:"Rumi", era:"Medieval Persia", type:"capsule", estMinutes:4, level:"Beginner",
    keyIdeas:["Love as the way","Remembrance of the divine","Joy in practice"],
    microPractices:["Practice one act of love","Remember the divine"], 
    reflections:["How did I express love today?"], audioUrl:null },
  { id:"sufi_heart", title:"Sufi Heart — Polishing the Mirror",
    thinker:"Various Sufi Masters", era:"Medieval", type:"capsule", estMinutes:4, level:"Intermediate",
    keyIdeas:["Purification of heart","Remembrance through breath","Service to others"],
    microPractices:["Practice heart purification","Serve with love"], 
    reflections:["How did I polish my heart today?"], audioUrl:null },

  // Ubuntu Resources
  { id:"ubuntu_philosophy", title:"Ubuntu — I Am Because We Are",
    thinker:"African Sages", era:"Timeless", type:"capsule", estMinutes:4, level:"Beginner",
    keyIdeas:["Interconnectedness","Humanity through others","Community strength"],
    microPractices:["Connect with one person today","Support community"], 
    reflections:["How did I practice ubuntu today?"], audioUrl:null },
  { id:"african_wisdom", title:"African Wisdom — Communal Living",
    thinker:"Various African Elders", era:"Timeless", type:"capsule", estMinutes:4, level:"Beginner",
    keyIdeas:["Elders' wisdom","Community responsibility","Generosity of spirit"],
    microPractices:["Learn from an elder","Practice generosity"], 
    reflections:["How did I honor community today?"], audioUrl:null },

  // High Performance Resources
  { id:"atomic_habits", title:"Atomic Habits — Systems Over Goals",
    thinker:"James Clear", era:"Modern", type:"capsule", estMinutes:5, level:"Beginner",
    keyIdeas:["Tiny changes","Identity-based habits","Environment design"],
    microPractices:["Make one habit obvious","Practice identity shift"], 
    reflections:["What identity am I building?"], audioUrl:null },
  { id:"deep_work", title:"Deep Work — Focus in Distracted Age",
    thinker:"Cal Newport", era:"Modern", type:"capsule", estMinutes:4, level:"Intermediate",
    keyIdeas:["Deep work","Attention management","Digital minimalism"],
    microPractices:["One deep work session","Eliminate one distraction"], 
    reflections:["How did I protect my attention today?"], audioUrl:null },

  // Universal Resources
  { id:"tao_soft_power", title:"Tao Te Ching — Soft Power",
    thinker:"Laozi", era:"Classical", type:"capsule", estMinutes:3, level:"Beginner",
    keyIdeas:["Non-forcing","Water's way"], 
    microPractices:["Soften one effort today"], 
    reflections:["Where can I do less but better?"], audioUrl:null },
  { id:"confucius_analects", title:"Analects — Cultivating Character",
    thinker:"Confucius", era:"Classical", type:"capsule", estMinutes:4, level:"Beginner",
    keyIdeas:["Ren (humaneness)","Li (ritual propriety)","Self-cultivation"],
    microPractices:["Practice one ritual today","Show kindness"], 
    reflections:["How did I cultivate character today?"], audioUrl:null },
]; 